import { hydrateMember, requireLead, useWorkspace } from "@/contexts/WorkspaceContext";

const stamp = () => Date.now();
const numericId = () => Date.now() + Math.floor(Math.random() * 1_000);
const queryHook = (select: (workspace: any, input: any) => any) => ({ useQuery: (input?: any) => { const workspace = useWorkspace(); return { data: workspace.profile ? select(workspace, input) : undefined, isLoading: workspace.loading, isError: Boolean(workspace.error), error: workspace.error, refetch: workspace.refresh }; } });
const mutationHook = (run: (workspace: any, input: any) => Promise<any>) => ({ useMutation: (options?: any) => { const workspace = useWorkspace(); let pending = false; return { get isPending() { return pending; }, mutate: async (input: any) => { pending = true; try { const value = await run(workspace, input); await options?.onSuccess?.(value); return value; } catch (reason) { options?.onError?.(reason instanceof Error ? reason : new Error("Action could not be completed.")); return undefined; } finally { pending = false; } } }; } });
const members = (workspace: any) => workspace.state.members.map((member: any) => member.status === "invited" ? { ...member, status: "active", invitationStatus: "invited" } : member);
const tasks = (workspace: any, input: any) => workspace.state.tasks.filter((task: any) => task.workDate === input.date).map((task: any) => { const assignee = hydrateMember(workspace.state, task.assignedTeamMemberId); return { ...task, assignee, member: assignee }; });
const handovers = (workspace: any, input: any) => workspace.state.handovers.filter((handover: any) => (!input?.status || handover.status === input.status) && (!input?.query || `${handover.title} ${handover.detail}`.toLowerCase().includes(input.query.toLowerCase()))).map((handover: any) => { const owner = hydrateMember(workspace.state, handover.ownerTeamMemberId); return { ...handover, owner, member: owner }; });
const issues = (workspace: any, input: any) => workspace.state.issues.filter((issue: any) => !input?.status || issue.status === input.status).map((issue: any) => ({ ...issue, owner: hydrateMember(workspace.state, issue.ownerTeamMemberId) }));
const dashboard = (workspace: any, input: any) => { const dailyTasks = tasks(workspace, input); const rota = workspace.state.rota.filter((item: any) => item.workDate === input.date).map((item: any) => ({ ...item, member: hydrateMember(workspace.state, item.teamMemberId) })); const readiness = workspace.state.readiness.filter((item: any) => item.pulseDate === input.date); const active = members(workspace).filter((member: any) => member.status === "active"); return { members: active, tasks: dailyTasks, rota, readiness, handovers: handovers(workspace, { status: "open" }), issues: issues(workspace, { status: "open" }), metrics: { totalTasks: dailyTasks.length, completeCount: dailyTasks.filter((task: any) => task.status === "complete").length, blockedCount: dailyTasks.filter((task: any) => task.status === "blocked").length, overdueCount: dailyTasks.filter((task: any) => task.dueAt && task.dueAt < stamp() && task.status !== "complete").length, readinessSubmitted: readiness.length, activeTeamMembers: active.length } }; };
const runtime: any = { useUtils: () => { const workspace = useWorkspace(); const invalidate = async () => workspace.refresh(); return { operations: { tasks: { list: { invalidate } }, dashboard: { invalidate } } }; }, operations: {
  access: { me: queryHook(workspace => workspace.profile) }, dashboard: queryHook(dashboard), team: { list: queryHook(workspace => members(workspace)), create: mutationHook(async (workspace, input) => { requireLead(workspace.profile); return workspace.createTeamMember({ ...input, status: "invited" }); }) },
  templates: { list: queryHook(workspace => workspace.state.templates), create: mutationHook(async (workspace, input) => { requireLead(workspace.profile); return workspace.add("templates", { id: numericId(), ...input, items: input.items || [] }); }), applyTemplate: mutationHook(async (workspace, input) => { requireLead(workspace.profile); const template = workspace.state.templates.find((item: any) => item.id === input.templateId); const created = template?.items?.length || 0; await Promise.all((template?.items || []).map((item: any) => workspace.add("tasks", { id: numericId(), workDate: input.workDate, title: item.title, detail: item.detail || null, priority: item.priority || "normal", status: "pending", dueAt: item.dueAt || null, assignedTeamMemberId: item.assignedTeamMemberId || null, blockedReason: null, completedAt: null }))); return { created }; }) },
  tasks: { list: queryHook(tasks), activity: queryHook((workspace, input) => workspace.state.activities.filter((item: any) => item.taskId === input.taskId).sort((a: any, b: any) => b.createdAt - a.createdAt)), create: mutationHook(async (workspace, input) => { requireLead(workspace.profile); const assignee = hydrateMember(workspace.state, input.assignedTeamMemberId); return workspace.add("tasks", { id: numericId(), ...input, assignedUserId: assignee?.userId || null, assignedEmail: assignee?.email || null, status: "pending", blockedReason: null, completedAt: null }); }), updateStatus: mutationHook(async (workspace, input) => { const task = workspace.state.tasks.find((item: any) => item.id === input.taskId); if (!task) throw new Error("Task was not found."); if (workspace.profile?.memberRole !== "lead" && task.assignedTeamMemberId !== workspace.profile?.id) throw new Error("You can only update work assigned to you."); await workspace.patch("tasks", task._docId, { status: input.status, blockedReason: input.status === "blocked" ? input.note || "Blocked" : null, completedAt: input.status === "complete" ? stamp() : null }); return workspace.add("activities", { id: numericId(), taskId: task.id, actorTeamMemberId: workspace.profile?.id, actorUserId: workspace.authUser?.uid, action: input.status, body: input.note || null }); }), comment: mutationHook(async (workspace, input) => workspace.add("activities", { id: numericId(), taskId: input.taskId, actorTeamMemberId: workspace.profile?.id, actorUserId: workspace.authUser?.uid, action: "comment", body: input.body })) },
  rota: { week: queryHook((workspace, input) => { const start = new Date(`${input.weekStart}T00:00:00`); const end = new Date(start); end.setDate(end.getDate() + 7); const endKey = end.toISOString().slice(0, 10); return { assignments: workspace.state.rota.filter((item: any) => item.workDate >= input.weekStart && item.workDate < endKey) }; }), create: mutationHook(async (workspace, input) => { requireLead(workspace.profile); return workspace.add("rota", { id: numericId(), ...input }); }), remove: mutationHook(async (workspace, input) => { requireLead(workspace.profile); const item = workspace.state.rota.find((row: any) => row.id === input.id); if (item) await workspace.remove("rota", item._docId); }) },
  handovers: { list: queryHook(handovers), create: mutationHook(async (workspace, input) => workspace.add("handovers", { id: numericId(), ...input, status: "open", acknowledgedByUserId: null, resolvedAt: null, resolution: null })), acknowledge: mutationHook(async (workspace, input) => { const item = workspace.state.handovers.find((row: any) => row.id === input.id); if (item) await workspace.patch("handovers", item._docId, { status: "acknowledged", acknowledgedByUserId: workspace.authUser?.uid }); }), resolve: mutationHook(async (workspace, input) => { const item = workspace.state.handovers.find((row: any) => row.id === input.id); if (item) await workspace.patch("handovers", item._docId, { status: "resolved", resolvedAt: stamp() }); }) },
  issues: { list: queryHook(issues), create: mutationHook(async (workspace, input) => workspace.add("issues", { id: numericId(), ...input, status: "open", resolution: null })), update: mutationHook(async (workspace, input) => { const item = workspace.state.issues.find((row: any) => row.id === input.id); if (item) await workspace.patch("issues", item._docId, input); }) },
  readiness: { list: queryHook((workspace, input) => workspace.state.readiness.filter((item: any) => item.pulseDate === input.date)), submit: mutationHook(async (workspace, input) => { if (!workspace.profile) throw new Error("Your team profile is not available yet."); const prior = workspace.state.readiness.find((item: any) => item.pulseDate === input.pulseDate && item.teamMemberId === workspace.profile.id); const value = { id: prior?.id || numericId(), pulseDate: input.pulseDate, teamMemberId: workspace.profile.id, userId: workspace.authUser?.uid, capacity: input.capacity, riskNote: input.riskNote || null, supportNeeded: input.supportNeeded || null }; if (prior) await workspace.patch("readiness", prior._docId, value); else await workspace.add("readiness", value); }) },
  performance: { overview: queryHook((workspace) => members(workspace).map((member: any) => { const owned = workspace.state.tasks.filter((task: any) => task.assignedTeamMemberId === member.id); const complete = owned.filter((task: any) => task.status === "complete"); const reasons = owned.filter((task: any) => task.status === "blocked" && task.blockedReason).map((task: any) => task.blockedReason); const recurringBlocker = reasons.sort((a: string, b: string) => reasons.filter((value: string) => value === b).length - reasons.filter((value: string) => value === a).length)[0] || null; return { member, assignedCount: owned.length, completionRate: owned.length ? Math.round(complete.length / owned.length * 100) : null, timelinessRate: complete.length ? Math.round(complete.filter((task: any) => !task.dueAt || task.completedAt <= task.dueAt).length / complete.length * 100) : null, blockedCount: reasons.length, recurringBlocker, shiftCount: workspace.state.rota.filter((item: any) => item.teamMemberId === member.id && ["early", "core", "late"].includes(item.assignmentType)).length, onCallCount: workspace.state.rota.filter((item: any) => item.teamMemberId === member.id && item.assignmentType === "on_call").length, notes: workspace.state.notes.filter((note: any) => note.teamMemberId === member.id).slice(0, 3) }; })), createNote: mutationHook(async (workspace, input) => { requireLead(workspace.profile); return workspace.add("notes", { id: numericId(), ...input }); }) }
} };
export const trpc: any = runtime;
