import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyState, LoadError, PageHeader, Panel, PanelHeading, TinyButton } from "@/components/WorkspacePrimitives";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { labelForStatus, priorityStyle } from "@/lib/operations";
import { trpc } from "@/lib/trpc";
import { CheckCheck, Clock3, Plus, Search, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Handovers() {
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"open" | "acknowledged" | "resolved" | "all">("open");
  const [form, setForm] = useState({ title: "", detail: "", priority: "normal", owner: "", deadline: "", decision: "" });
  const team = trpc.operations.team.list.useQuery();
  const handovers = trpc.operations.handovers.list.useQuery({ query: query || undefined, status: status === "all" ? undefined : status });
  const create = trpc.operations.handovers.create.useMutation({ onSuccess: async () => { await handovers.refetch(); setOpen(false); setForm({ title: "", detail: "", priority: "normal", owner: "", deadline: "", decision: "" }); toast.success("Handover added to the decision record."); }, onError: error => toast.error(error.message) });
  const acknowledge = trpc.operations.handovers.acknowledge.useMutation({ onSuccess: async () => { await handovers.refetch(); toast.success("Handover acknowledged."); }, onError: error => toast.error(error.message) });
  const resolve = trpc.operations.handovers.resolve.useMutation({ onSuccess: async () => { await handovers.refetch(); toast.success("Handover resolved and closed."); }, onError: error => toast.error(error.message) });
  const submit = () => { if (!form.title.trim() || !form.detail.trim()) return toast.error("Include both a clear headline and the operational context."); create.mutate({ title: form.title, detail: form.detail, priority: form.priority as "low" | "normal" | "high" | "critical", ownerTeamMemberId: form.owner ? Number(form.owner) : undefined, deadlineAt: form.deadline ? new Date(form.deadline).getTime() : undefined, decisionRecord: form.decision || undefined }); };
  const summary = { open: handovers.data?.filter(item => item.status === "open").length ?? 0, acknowledged: handovers.data?.filter(item => item.status === "acknowledged").length ?? 0, resolved: handovers.data?.filter(item => item.status === "resolved").length ?? 0 };
  if (team.isError || handovers.isError) return <LoadError message="The handover register could not be loaded. Your records remain unchanged." onRetry={() => void Promise.all([team.refetch(), handovers.refetch()])} />;
  return <div className="mx-auto max-w-[1300px] pb-10"><PageHeader eyebrow="Continuity and decision record" title="Shift handovers" description="Capture context, decisions and ownership in one deliberate record—so nothing important gets lost between people or shifts." actions={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#1D5C63] hover:bg-[#164B50]"><Plus className="mr-2 h-4 w-4" />New handover</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Create a structured handover</DialogTitle><DialogDescription>Write what the next owner needs to know, decide or do.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="space-y-2"><Label>Headline</Label><Input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Late cover for airport transfer still unconfirmed" /></div><div className="space-y-2"><Label>Operational context</Label><Textarea className="min-h-28" value={form.detail} onChange={event => setForm({ ...form, detail: event.target.value })} placeholder="What happened, why it matters and what has already been tried?" /></div><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label>Priority</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.priority} onChange={event => setForm({ ...form, priority: event.target.value })}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></div><div className="space-y-2"><Label>Named owner</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.owner} onChange={event => setForm({ ...form, owner: event.target.value })}><option value="">Unassigned</option>{team.data?.filter(member => member.status === "active").map(member => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></div><div className="space-y-2"><Label>Deadline</Label><Input type="datetime-local" value={form.deadline} onChange={event => setForm({ ...form, deadline: event.target.value })} /></div></div><div className="space-y-2"><Label>Decision record</Label><Textarea value={form.decision} onChange={event => setForm({ ...form, decision: event.target.value })} placeholder="Decision made, rationale or constraints (optional)" /></div></div><DialogFooter><Button onClick={submit} disabled={create.isPending} className="bg-[#1D5C63] hover:bg-[#164B50]">Record handover</Button></DialogFooter></DialogContent></Dialog>} />
    <section className="mb-6 grid gap-4 sm:grid-cols-3"><Summary label="Open" value={summary.open} tint="red" /><Summary label="Acknowledged" value={summary.acknowledged} tint="amber" /><Summary label="Resolved" value={summary.resolved} tint="green" /></section>
    <Panel><PanelHeading title="Handover register" description="Search the live and historic decision record." action={<div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-[#89948F]" /><Input value={query} onChange={event => setQuery(event.target.value)} className="h-8 w-44 pl-8 text-xs" placeholder="Search record" /></div><select className="h-8 rounded-md border border-input bg-background px-2 text-xs" value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="all">All records</option></select></div>} /><div className="divide-y divide-[#EDF0EE]">{handovers.isLoading ? <LoadingRows /> : handovers.data?.length ? handovers.data.map(item => <article className="px-5 py-5" key={item.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge className={`border-0 px-2 py-0.5 text-[9px] uppercase tracking-[0.08em] ${priorityStyle[item.priority]}`}>{item.priority}</Badge><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${item.status === "open" ? "bg-[#FFF0EE] text-[#B8473B]" : item.status === "acknowledged" ? "bg-[#FFF4E2] text-[#A56520]" : "bg-[#E9F4ED] text-[#337454]"}`}>{labelForStatus(item.status)}</span></div><h3 className="mt-3 text-[15px] font-semibold text-[#2B3933]">{item.title}</h3><p className="mt-1.5 max-w-3xl text-sm leading-6 text-[#66736D]">{item.detail}</p>{item.decisionRecord ? <div className="mt-3 rounded-xl bg-[#F3F7F5] px-3 py-2.5 text-xs leading-5 text-[#4E625A]"><strong>Decision record:</strong> {item.decisionRecord}</div> : null}</div><div className="flex shrink-0 items-center gap-2"><span className="rounded-full bg-[#F0F3F1] px-2.5 py-1 text-[10px] font-semibold text-[#66736D]">{item.owner?.displayName || "No owner"}</span>{item.deadlineAt ? <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-[#69756F]"><Clock3 className="h-3 w-3" />{new Date(item.deadlineAt).toLocaleString([], { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span> : null}</div></div><div className="mt-4 flex flex-wrap gap-2">{item.status === "open" ? <TinyButton disabled={acknowledge.isPending} onClick={() => acknowledge.mutate({ id: item.id })}><CheckCheck className="mr-1.5 h-3.5 w-3.5" />Acknowledge</TinyButton> : null}{item.status !== "resolved" ? <TinyButton disabled={resolve.isPending} onClick={() => resolve.mutate({ id: item.id })}><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Resolve</TinyButton> : null}</div></article>) : <EmptyState title="No handovers match this view" description="Use the new handover action to record the first piece of operational continuity." />}</div></Panel>
  </div>;
}
function Summary({ label, value, tint }: { label: string; value: number; tint: "red" | "amber" | "green" }) { const style = { red: "border-[#F1D5D0] bg-[#FFFAF9] text-[#B5463B]", amber: "border-[#F3E0C8] bg-[#FFFCF7] text-[#A56621]", green: "border-[#D6E9DE] bg-[#F8FBF9] text-[#397556]" }[tint]; return <div className={`rounded-2xl border px-5 py-4 ${style}`}><p className="text-[10px] font-bold uppercase tracking-[0.14em] opacity-75">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function LoadingRows() { return <div className="space-y-4 px-5 py-5">{[1, 2, 3].map(key => <div className="h-24 animate-pulse rounded-xl bg-[#F2F5F3]" key={key} />)}</div>; }
