import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { LoadError } from "@/components/WorkspacePrimitives";
import { trpc } from "@/lib/trpc";
import { compactTime, dateTitle, labelForStatus, localDateKey, priorityStyle } from "@/lib/operations";
import { AlertTriangle, ArrowRight, Check, ChevronRight, ClipboardCheck, Clock3, Loader2, RadioTower, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

export default function Home() {
  const { user } = useAuth();
  const [today] = useState(localDateKey());
  const dashboard = trpc.operations.dashboard.useQuery({ date: today });
  const snapshot = dashboard.data;
  const metrics = snapshot?.metrics;
  const firstName = user?.name?.split(" ")[0] || "there";
  const onCall = snapshot?.rota.find(item => item.assignmentType === "on_call")?.member;
  const signals = snapshot?.signals;

  if (dashboard.isLoading) return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#1D5C63]" /></div>;
  if (dashboard.isError) return <LoadError message="The live command board is temporarily unavailable." onRetry={() => void dashboard.refetch()} />;

  return <div className="mx-auto max-w-[1500px] pb-10">
    <header className="flex flex-col gap-5 border-b border-[#E3E9E5] pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#71817A]">Today · {dateTitle(today)}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-[#1C2924]">Good morning, {firstName}.</h1><p className="mt-2 text-sm text-[#69756F]">Here is the operating picture — what needs attention, who owns it and where support is needed.</p></div><div className="flex gap-2"><Link href="/tasks"><Button variant="outline" className="border-[#D6E3DE] bg-white">Open task board<ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/handover"><Button className="bg-[#1D5C63] hover:bg-[#164B50]">Log a handover</Button></Link></div></header>
    {user?.isSuperuser && signals ? <OperationalSignals signals={signals} /> : null}

    {!snapshot?.members.length ? <OnboardingPanel /> : <>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Daily completion" value={metrics?.totalTasks ? `${Math.round(((metrics.completeCount ?? 0) / metrics.totalTasks) * 100)}%` : "—"} support={metrics?.totalTasks ? `${metrics.completeCount} of ${metrics.totalTasks} tasks complete` : "No tasks created"} icon={<ClipboardCheck className="h-5 w-5" />} tint="teal" /><Metric label="Needs attention" value={metrics?.overdueCount ?? 0} support={metrics?.overdueCount ? "Overdue tasks on board" : "Nothing overdue"} icon={<Clock3 className="h-5 w-5" />} tint="amber" /><Metric label="Open exceptions" value={(metrics?.blockedCount ?? 0) + (snapshot?.issues.length ?? 0)} support={`${metrics?.blockedCount ?? 0} blocked · ${snapshot?.issues.length ?? 0} in issue log`} icon={<AlertTriangle className="h-5 w-5" />} tint="red" /><Metric label="On-call cover" value={onCall ? "Covered" : "Missing"} support={onCall ? `${onCall.displayName} is named for continuity` : "Assign an on-call lead"} icon={<RadioTower className="h-5 w-5" />} tint={onCall ? "green" : "amber"} /></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.7fr)]"><div className="overflow-hidden rounded-2xl border border-[#E0E7E2] bg-white shadow-[0_18px_38px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-center justify-between border-b border-[#EDF0EE] px-5 py-4"><div><h2 className="text-base font-semibold text-[#23312C]">Today’s command board</h2><p className="mt-0.5 text-xs text-[#74817C]">The work most likely to determine today’s service quality.</p></div><Link href="/tasks" className="text-xs font-semibold text-[#1D5C63] hover:underline">All tasks</Link></div><div>{snapshot.tasks.length ? snapshot.tasks.slice(0, 6).map(task => <div key={task.id} className="flex items-center gap-3 border-b border-[#F0F2F1] px-5 py-3.5 last:border-0"><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${task.status === "complete" ? "border-[#2F7B59] bg-[#2F7B59] text-white" : "border-[#C5D0CA] text-transparent"}`}><Check className="h-3 w-3" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#2B3833]">{task.title}</p><div className="mt-1 flex items-center gap-2"><Badge className={`border-0 px-2 py-0.5 text-[9px] uppercase tracking-[0.08em] ${priorityStyle[task.priority]}`}>{task.priority}</Badge><span className="text-[11px] text-[#7A8580]">{task.member?.displayName || "Unassigned"}</span></div></div><div className="text-right"><p className={`text-xs font-semibold ${task.dueAt && task.dueAt < Date.now() && task.status !== "complete" ? "text-[#B94336]" : "text-[#606C66]"}`}>{compactTime(task.dueAt)}</p><p className="mt-1 text-[10px] capitalize text-[#8A948F]">{labelForStatus(task.status)}</p></div></div>) : <BoardEmpty />}</div></div>
        <aside className="space-y-5"><div className="rounded-2xl bg-[#1C3732] px-5 py-5 text-white shadow-[0_18px_38px_-22px_rgba(18,48,41,0.72)]"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#B9D3C9]">On-call control</p><RadioTower className="h-4 w-4 text-[#B9D3C9]" /></div><p className="mt-5 text-2xl font-semibold tracking-tight">{onCall?.displayName || "Not assigned"}</p><p className="mt-1 text-sm text-[#C8DAD3]">{onCall ? "Named lead for out-of-hours continuity." : "Assign a lead before the day closes."}</p><Link href="/rota"><Button variant="ghost" className="mt-5 h-9 bg-white/10 px-0 text-xs text-white hover:bg-white/15 hover:text-white">Review weekly cover <ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></Link></div><div className="rounded-2xl border border-[#E0E7E2] bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#28352F]">Today’s continuity</p><p className="mt-0.5 text-xs text-[#7A8680]">Open handovers and active exceptions.</p></div><ShieldCheck className="h-5 w-5 text-[#4C856E]" /></div><div className="mt-4 grid grid-cols-2 gap-2"><SignalStat label="Handovers" value={snapshot?.handovers.length ?? 0} className="bg-[#FFF4E4] text-[#A66622]" /><SignalStat label="Issues" value={snapshot?.issues.length ?? 0} className="bg-[#FFF0EE] text-[#B34D40]" /></div><div className="mt-4 grid grid-cols-2 gap-2"><Link href="/handover"><Button variant="outline" size="sm" className="w-full border-[#DCE6E0] text-xs">Handovers</Button></Link><Link href="/issues"><Button variant="outline" size="sm" className="w-full border-[#DCE6E0] text-xs">Issue log</Button></Link></div></div></aside>
      </section>

      <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[#E0E7E2] bg-white shadow-[0_18px_38px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-center justify-between border-b border-[#EDF0EE] px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#EEF3F1] text-[#397167]"><ShieldCheck className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-[#28352F]">Live handovers</h2><p className="text-xs text-[#77847E]">Nothing should be lost between shifts.</p></div></div><Link href="/handover" className="text-xs font-semibold text-[#1D5C63] hover:underline">Open register</Link></div><div className="divide-y divide-[#F0F2F1]">{snapshot.handovers.length ? snapshot.handovers.slice(0, 3).map(handover => <div key={handover.id} className="flex gap-3 px-5 py-4"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${handover.priority === "critical" ? "bg-[#C84D3B]" : handover.priority === "high" ? "bg-[#DD9B39]" : "bg-[#5C9780]"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#35423D]">{handover.title}</p><p className="mt-1 line-clamp-1 text-xs text-[#77837D]">{handover.detail}</p></div><span className="shrink-0 text-[11px] font-semibold text-[#63706A]">{handover.member?.initials || "—"}</span></div>) : <CompactEmpty text="No open handovers — the decision record is clear." />}</div></div>
        <div className="rounded-2xl border border-[#E0E7E2] bg-white shadow-[0_18px_38px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-center justify-between border-b border-[#EDF0EE] px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#FFF2E8] text-[#B66B25]"><AlertTriangle className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-[#28352F]">Operational exceptions</h2><p className="text-xs text-[#77847E]">Active exceptions with a named next action.</p></div></div><Link href="/issues" className="text-xs font-semibold text-[#1D5C63] hover:underline">Issue log</Link></div><div className="divide-y divide-[#F0F2F1]">{snapshot.issues.length ? snapshot.issues.slice(0, 3).map(issue => <div key={issue.id} className="flex gap-3 px-5 py-4"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${issue.impact === "critical" || issue.impact === "high" ? "bg-[#C84D3B]" : "bg-[#DD9B39]"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#35423D]">{issue.title}</p><p className="mt-1 line-clamp-1 text-xs text-[#77837D]">Next: {issue.nextAction}</p></div><span className="shrink-0 text-[10px] font-bold uppercase tracking-[0.1em] text-[#76827C]">{issue.category.replace("_", " ")}</span></div>) : <CompactEmpty text="No open issues have been recorded." />}</div></div></section>
    </>}
  </div>;
}

function Metric({ label, value, support, icon, tint }: { label: string; value: string | number; support: string; icon: React.ReactNode; tint: "teal" | "amber" | "red" | "green" }) { const colour = { teal: "bg-[#E9F2EF] text-[#347167]", amber: "bg-[#FFF4E4] text-[#AF6D24]", red: "bg-[#FFF0EE] text-[#B94B3E]", green: "bg-[#EAF4EE] text-[#357754]" }[tint]; return <div className="rounded-2xl border border-[#E1E8E3] bg-white px-5 py-4 shadow-[0_16px_36px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-start justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#77847E]">{label}</p><span className={`flex h-8 w-8 items-center justify-center rounded-xl ${colour}`}>{icon}</span></div><p className="mt-4 text-2xl font-semibold tracking-tight text-[#26342F]">{value}</p><p className="mt-1 text-xs text-[#7B8781]">{support}</p></div>; }
function SignalStat({ label, value, className }: { label: string; value: number; className: string }) { return <div className={`rounded-xl px-2 py-3 text-center ${className}`}><p className="text-lg font-semibold">{value}</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-[0.08em] opacity-75">{label}</p></div>; }
function CompactEmpty({ text }: { text: string }) { return <p className="px-5 py-7 text-center text-xs text-[#85908B]">{text}</p>; }
function BoardEmpty() { return <div className="px-6 py-10 text-center"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-[#EAF3EE] text-[#3E816A]"><ClipboardCheck className="h-5 w-5" /></span><p className="mt-3 text-sm font-semibold text-[#34413C]">The board is waiting for its first task.</p><Link href="/tasks" className="mt-2 inline-block text-xs font-semibold text-[#1D5C63] hover:underline">Create a daily checklist</Link></div>; }
function OnboardingPanel() { return <section className="mt-7 overflow-hidden rounded-3xl bg-[#1C3732] px-6 py-9 text-white shadow-[0_24px_52px_-28px_rgba(14,44,37,0.7)] md:px-10"><div className="max-w-2xl"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/10"><UsersRound className="h-5 w-5 text-[#D8EBE4]" /></div><p className="mt-6 text-[11px] font-bold uppercase tracking-[0.16em] text-[#BBD2C9]">Set up your command centre</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Start with the six people who make the operation run.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#C4D8D0]">Create the team, then add the daily checks and rota routines you already use. The command board will make the live work and risks visible from day one.</p><Link href="/people"><Button className="mt-6 bg-white text-[#1C3732] hover:bg-[#EDF6F1]">Create the team <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></section>; }
function OperationalSignals({ signals }: { signals: any }) { const prompts = [signals.uncoveredDuties.length ? `${signals.uncoveredDuties.map((duty: string) => duty.replace("_", " ")).join(", ")} cover missing` : null, signals.unownedTasks.length ? `${signals.unownedTasks.length} unowned task${signals.unownedTasks.length === 1 ? "" : "s"}` : null, signals.unownedHelpRequests.length ? `${signals.unownedHelpRequests.length} help request${signals.unownedHelpRequests.length === 1 ? "" : "s"} waiting for an owner` : null].filter(Boolean); if (!prompts.length) return <section className="mt-5 flex items-center gap-3 rounded-2xl border border-[#D7E9DE] bg-[#F7FBF8] px-5 py-3.5 text-sm text-[#41705C]"><Check className="h-4 w-4" />Operational signals are complete for the information recorded today.</section>; return <section className="mt-5 flex flex-col gap-3 rounded-2xl border border-[#F0DCC2] bg-[#FFF9F3] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#AD6A27]" /><div><p className="text-sm font-semibold text-[#5B472F]">Operational signals to close</p><p className="mt-1 text-xs leading-5 text-[#79654B]">{prompts.join(" · ")}. These are missing operational inputs, not a staff performance score.</p></div></div><Link href="/help"><Button size="sm" variant="outline" className="shrink-0 border-[#E6CDAE] bg-white text-[#7B5326]">Coordinate help</Button></Link></section>; }
