import { PageHeader } from "@/components/WorkspacePrimitives";
import { InitialsCircle } from "@/components/ColleagueMarker";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Palette, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const palette = ["#1D5C63", "#355C9A", "#7A4E92", "#B04E57", "#B26B28", "#397B60", "#4F6B7A", "#825A45"];
export default function Profile() { const workspace = useWorkspace(); const profile = workspace.profile; const [initials, setInitials] = useState(profile?.initials || ""); const [colour, setColour] = useState(profile?.colour || palette[0]); const update = trpc.operations.team.updateSelf.useMutation({ onSuccess: () => toast.success("Your initials and colour are now visible across the workspace."), onError: (error: Error) => toast.error(error.message) }); if (!profile) return null; const marker = { ...profile, initials, colour }; return <div className="mx-auto max-w-2xl pb-10"><PageHeader eyebrow="Your workspace identity" title="My initials & colour" description="Choose the coloured initials marker colleagues will see beside work you own, complete or hand over." /><section className="rounded-3xl border border-[#DEE7E2] bg-white p-6 shadow-[0_18px_38px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-center gap-4 rounded-2xl bg-[#F5F8F6] p-5"><InitialsCircle member={marker} size="lg" active /><div><p className="text-base font-semibold text-[#2C4036]">{profile.displayName}</p><p className="mt-1 text-xs text-[#75817B]">Your marker is shown with a green dot while you are active in the workspace.</p></div></div><div className="mt-6 space-y-6"><div className="space-y-2"><Label htmlFor="initials">Initials</Label><Input id="initials" value={initials} maxLength={3} onChange={event => setInitials(event.target.value.toUpperCase().replace(/[^A-Z]/g, ""))} placeholder="BC" /><p className="text-xs text-[#77847E]">Use one to three letters. Your name and access level remain managed separately.</p></div><div className="space-y-3"><Label>Marker colour</Label><div className="flex flex-wrap gap-3">{palette.map(value => <button key={value} type="button" aria-label={`Use colour ${value}`} onClick={() => setColour(value)} className={`h-9 w-9 rounded-full border-2 transition-transform ${colour === value ? "scale-110 border-[#233B31]" : "border-white"}`} style={{ backgroundColor: value }} />)}<label className="flex h-9 items-center gap-2 rounded-full border border-[#D8E2DC] bg-white px-3 text-xs text-[#56665F]"><Palette className="h-3.5 w-3.5" />Custom<input aria-label="Custom marker colour" type="color" value={colour} onChange={event => setColour(event.target.value)} className="h-5 w-5 cursor-pointer border-0 bg-transparent p-0" /></label></div></div><Button disabled={update.isPending || !initials} onClick={() => update.mutate({ initials, colour })} className="w-full bg-[#1D5C63] hover:bg-[#164B50]"><CheckCircle2 className="mr-2 h-4 w-4" />Save my marker</Button></div></section><section className="mt-5 flex gap-3 rounded-2xl border border-[#DCE7E1] bg-[#F8FBF9] p-4 text-xs leading-5 text-[#607169]"><UserRound className="mt-0.5 h-4 w-4 shrink-0 text-[#3E7D68]" />This is a shared collaboration signal. The presence dot means the person has recently had the workspace open; it does not track screen time, location or productivity.</section></div>; }
