import { EmptyState, LoadError, PageHeader, Panel, PanelHeading } from "@/components/WorkspacePrimitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { localDateKey } from "@/lib/operations";
import { trpc } from "@/lib/trpc";
import { HeartPulse, Plus, ShieldAlert, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const capacityStyle: Record<string, string> = { green: "border-[#CBE4D5] bg-[#ECF7F0] text-[#317754]", amber: "border-[#F0DEC1] bg-[#FFF7E8] text-[#A56A23]", red: "border-[#F0CFC9] bg-[#FFF0EE] text-[#B6493E]" };

export default function Readiness() {
  const [today] = useState(localDateKey()); const [open, setOpen] = useState(false); const [form, setForm] = useState({ capacity: "green", riskNote: "", supportNeeded: "" });
  const team = trpc.operations.team.list.useQuery(); const pulses = trpc.operations.readiness.list.useQuery({ date: today }); const access = trpc.operations.access.me.useQuery();
  const submit = trpc.operations.readiness.submit.useMutation({ onSuccess: async () => { await pulses.refetch(); setOpen(false); setForm({ capacity: "green", riskNote: "", supportNeeded: "" }); toast.success("Readiness pulse recorded."); }, onError: error => toast.error(error.message) });
  const activeMembers = team.data?.filter(member => member.status === "active") ?? [];
  const pulseFor = (memberId: number) => pulses.data?.find(pulse => pulse.teamMemberId === memberId);
  const counts = { green: pulses.data?.filter(pulse => pulse.capacity === "green").length ?? 0, amber: pulses.data?.filter(pulse => pulse.capacity === "amber").length ?? 0, red: pulses.data?.filter(pulse => pulse.capacity === "red").length ?? 0 };
  const send = () => { if (!access.data) return toast.error("Your account must first be linked to the team directory using the same work email."); submit.mutate({ pulseDate: today, capacity: form.capacity as "green" | "amber" | "red", riskNote: form.riskNote || undefined, supportNeeded: form.supportNeeded || undefined }); };
  if (team.isError || pulses.isError || access.isError) return <LoadError message="The readiness view could not be loaded. No pulse has been recorded." onRetry={() => void Promise.all([team.refetch(), pulses.refetch(), access.refetch()])} />;
  return <div className="mx-auto max-w-[1200px] pb-10"><PageHeader eyebrow="Daily capacity and support signal" title="Team readiness pulse" description="A simple early-warning habit: each person flags capacity, emerging risk and support needed before those conditions become service failures." actions={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#1D5C63] hover:bg-[#164B50]"><Plus className="mr-2 h-4 w-4" />Submit pulse</Button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Submit a readiness pulse</DialogTitle><DialogDescription>This is not a performance score. It makes support needs visible early and constructively.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="rounded-xl border border-[#DCE7E1] bg-[#F4F8F6] px-3 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#718179]">Submitting as</p><p className="mt-1 text-sm font-semibold text-[#34423B]">{access.data?.displayName || "Team profile not linked"}</p></div><div className="space-y-2"><Label>Current capacity</Label><div className="grid grid-cols-3 gap-2">{(["green", "amber", "red"] as const).map(capacity => <button key={capacity} onClick={() => setForm({ ...form, capacity })} className={`rounded-xl border px-3 py-3 text-left transition-all ${form.capacity === capacity ? capacityStyle[capacity] : "border-[#E0E6E2] bg-white text-[#66736D]"}`}><p className="text-sm font-semibold capitalize">{capacity}</p><p className="mt-1 text-[10px] leading-4 opacity-75">{capacity === "green" ? "Capacity is sound" : capacity === "amber" ? "Pressure needs watching" : "Support is needed"}</p></button>)}</div></div><div className="space-y-2"><Label>Risk or constraint</Label><Textarea value={form.riskNote} onChange={event => setForm({ ...form, riskNote: event.target.value })} placeholder="Anything likely to create operational pressure?" /></div><div className="space-y-2"><Label>Support needed</Label><Textarea value={form.supportNeeded} onChange={event => setForm({ ...form, supportNeeded: event.target.value })} placeholder="The most helpful action from the team or lead…" /></div></div><DialogFooter><Button disabled={submit.isPending || !access.data} onClick={send} className="bg-[#1D5C63] hover:bg-[#164B50]">Record pulse</Button></DialogFooter></DialogContent></Dialog>} />
  <section className="mb-6 grid gap-4 sm:grid-cols-3"><PulseStat label="Clear capacity" count={counts.green} style="bg-[#ECF7F0] text-[#327755]" /><PulseStat label="Watch points" count={counts.amber} style="bg-[#FFF6E7] text-[#A46721]" /><PulseStat label="Support required" count={counts.red} style="bg-[#FFF0EE] text-[#B6493E]" /></section><Panel><PanelHeading title="Today’s team check-in" description={`${pulses.data?.length ?? 0} of ${activeMembers.length} readiness pulses recorded.`} /><div className="divide-y divide-[#EDF0EE]">{activeMembers.length ? activeMembers.map(member => { const pulse = pulseFor(member.id); return <div key={member.id} className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-start"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: member.colour }}>{member.initials}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[#33413B]">{member.displayName}</p>{pulse ? <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold capitalize ${capacityStyle[pulse.capacity]}`}>{pulse.capacity} capacity</span> : <span className="rounded-full bg-[#F1F3F2] px-2.5 py-1 text-[10px] font-semibold text-[#78847E]">Awaiting pulse</span>}</div>{pulse ? <div className="mt-3 grid gap-3 sm:grid-cols-2">{pulse.riskNote ? <Note icon={<ShieldAlert className="h-3.5 w-3.5" />} label="Risk / constraint" body={pulse.riskNote} /> : <Note icon={<HeartPulse className="h-3.5 w-3.5" />} label="Risk / constraint" body="No risk reported." muted />}{pulse.supportNeeded ? <Note icon={<UsersRound className="h-3.5 w-3.5" />} label="Support needed" body={pulse.supportNeeded} /> : <Note icon={<UsersRound className="h-3.5 w-3.5" />} label="Support needed" body="No additional support requested." muted />}</div> : <p className="mt-2 text-xs text-[#818C87]">No readiness signal received yet.</p>}</div></div>; }) : <EmptyState title="Set up the team to start daily pulses" description="Create the team directory first. It will become the list used for rota cover, handovers, tasks and readiness." />}</div></Panel></div>;
}
function PulseStat({ label, count, style }: { label: string; count: number; style: string }) { return <div className={`rounded-2xl px-5 py-4 ${style}`}><p className="text-[10px] font-bold uppercase tracking-[0.14em] opacity-75">{label}</p><p className="mt-2 text-2xl font-semibold">{count}</p></div>; }
function Note({ icon, label, body, muted }: { icon: React.ReactNode; label: string; body: string; muted?: boolean }) { return <div className={`rounded-xl px-3 py-3 ${muted ? "bg-[#F6F8F7] text-[#7B8781]" : "bg-[#F2F7F4] text-[#53635C]"}`}><p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.1em]"><span>{icon}</span>{label}</p><p className="mt-1.5 text-xs leading-5">{body}</p></div>; }
