import { useAuth } from "@/_core/hooks/useAuth";
import { LoadError, PageHeader } from "@/components/WorkspacePrimitives";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { localDateKey } from "@/lib/operations";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardCheck, Loader2, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const today = localDateKey();
const dutyChecks: Record<string, string[]> = { early: ["Review overnight changes and the first departures", "Confirm early cover and urgent service risks"], core: ["Review active service changes and owner actions", "Confirm cover and client follow-up priorities"], late: ["Review remaining service commitments and late cover", "Prepare open actions for the next duty"], on_call: ["Review the named on-call handover and current open actions", "Confirm the escalation route and next available support"], default: ["Review urgent shared context", "Confirm the next operational priority"] };

export default function ShiftCheck() {
  const { user } = useAuth(); const workspace = useWorkspace(); const [phase, setPhase] = useState<"start" | "close">("start"); const [reviewed, setReviewed] = useState(false); const [checkedItems, setCheckedItems] = useState<string[]>([]); const [riskNote, setRiskNote] = useState(""); const [nextOwner, setNextOwner] = useState(""); const [nextAction, setNextAction] = useState("");
  const team = trpc.operations.team.list.useQuery(); const handovers = trpc.operations.handovers.list.useQuery({ status: "open" }); const prompts = trpc.operations.shiftPrompts.list.useQuery({ date: today }); const acknowledge = trpc.operations.handovers.acknowledge.useMutation({ onSuccess: () => toast.success("Handover acknowledged."), onError: (error: Error) => toast.error(error.message) });
  const assignment = useMemo(() => workspace.state.rota.find((item: any) => item.workDate === today && item.teamMemberId === workspace.profile?.id), [workspace.state.rota, workspace.profile]);
  const submit = trpc.operations.shiftPrompts.submit.useMutation({ onSuccess: () => { toast.success(phase === "start" ? "Shift start recorded." : "Shift close recorded."); setCheckedItems([]); setRiskNote(""); setNextOwner(""); setNextAction(""); }, onError: (error: Error) => toast.error(error.message) });
  const prior = prompts.data?.find((prompt: any) => prompt.phase === phase); const canAct = Boolean(user?.canUseOnCall); const canAcknowledge = Boolean(user?.canEditSharedWork); const checklist = dutyChecks[assignment?.assignmentType || "default"] || dutyChecks.default;
  if (workspace.loading) return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#1D5C63]" /></div>;
  if (workspace.error) return <LoadError message="The shift check could not be loaded. No operational record has been changed." onRetry={() => void workspace.refresh()} />;
  return <div className="mx-auto max-w-2xl pb-10"><PageHeader eyebrow="Short, duty-aware check" title={phase === "start" ? "Start my shift" : "Close my shift"} description={phase === "start" ? "Review the important context, then flag anything that needs a named owner." : "Leave the next person a clear handover, or record the support you need before you finish."} />
    <div className="mb-5 grid grid-cols-2 rounded-2xl border border-[#DDE7E2] bg-white p-1"><button onClick={() => setPhase("start")} className={`rounded-xl px-4 py-3 text-sm font-semibold ${phase === "start" ? "bg-[#1D5C63] text-white" : "text-[#68776F]"}`}>Start shift</button><button onClick={() => setPhase("close")} className={`rounded-xl px-4 py-3 text-sm font-semibold ${phase === "close" ? "bg-[#1D5C63] text-white" : "text-[#68776F]"}`}>Close shift</button></div>
    <section className="rounded-3xl border border-[#DFE8E3] bg-white p-6 shadow-[0_18px_38px_-32px_rgba(18,48,41,0.46)]"><div className="flex items-start gap-3 rounded-2xl bg-[#F4F8F6] p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#E1F0E8] text-[#37795F]"><ClipboardCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#31443A]">{assignment ? `Today’s ${String(assignment.assignmentType).replace("_", " ")} duty` : "No rota duty recorded"}</p><p className="mt-1 text-xs leading-5 text-[#718077]">{handovers.data?.length || 0} open handover{handovers.data?.length === 1 ? "" : "s"} are available to review. This check is short by design—record only what the next person needs.</p></div></div><div className="mt-5 rounded-2xl border border-[#E4ECE7] bg-[#FBFCFB] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#71827A]">Essential for this duty</p><div className="mt-3 space-y-3">{checklist.map(item => <div key={item} className="flex items-start gap-3"><Checkbox id={item} checked={checkedItems.includes(item) || Boolean(prior?.checklist?.includes(item))} onCheckedChange={value => setCheckedItems(current => value === true ? [...current, item] : current.filter(value => value !== item))} disabled={Boolean(prior)} /><Label htmlFor={item} className="cursor-pointer text-sm leading-5 text-[#45564E]">{item}</Label></div>)}</div></div>{handovers.data?.length ? <div className="mt-4 rounded-2xl border border-[#E4ECE7] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#71827A]">Open handovers</p><div className="mt-3 space-y-2">{handovers.data.slice(0, 3).map((handover: any) => <div key={handover.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#F7FAF8] px-3 py-2"><p className="min-w-0 truncate text-xs font-semibold text-[#405249]">{handover.title}</p>{handover.status === "open" && canAcknowledge ? <Button size="sm" variant="outline" disabled={acknowledge.isPending} onClick={() => acknowledge.mutate({ id: handover.id })}>Acknowledge</Button> : <span className="text-[10px] text-[#718077]">{handover.status}</span>}</div>)}</div></div> : null}
      <div className="mt-5 space-y-5"><div className="flex items-start gap-3"><Checkbox id="handover" checked={reviewed || Boolean(prior?.handoverReviewed)} onCheckedChange={value => setReviewed(value === true)} disabled={Boolean(prior)} /><Label htmlFor="handover" className="cursor-pointer text-sm leading-6">I have reviewed the relevant open handovers and urgent shared context.</Label></div><div className="space-y-2"><Label>Risk or support needed <span className="font-normal text-[#7C8982]">(optional)</span></Label><Textarea value={riskNote} onChange={event => setRiskNote(event.target.value)} disabled={Boolean(prior)} placeholder={phase === "start" ? "What might put today’s service under pressure?" : "What still needs watching after your shift?"} /></div>{phase === "close" ? <><div className="space-y-2"><Label>Next owner <span className="font-normal text-[#7C8982]">(optional)</span></Label><select value={nextOwner} onChange={event => setNextOwner(event.target.value)} disabled={Boolean(prior)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">No owner chosen here</option>{team.data?.filter((member: any) => member.status === "active").map((member: any) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></div><div className="space-y-2"><Label>Next action <span className="font-normal text-[#7C8982]">(optional)</span></Label><Input value={nextAction} onChange={event => setNextAction(event.target.value)} disabled={Boolean(prior)} placeholder="For example, check confirmed late cover at 15:00" /></div></> : null}</div>
      {prior ? <div className="mt-6 flex items-center gap-2 rounded-xl bg-[#EAF5EE] px-4 py-3 text-sm text-[#3D7158]"><CheckCircle2 className="h-4 w-4" />This {phase} check was already recorded today.</div> : <Button disabled={!canAct || submit.isPending} onClick={() => submit.mutate({ workDate: today, phase, handoverReviewed: reviewed, checklist: checkedItems, riskNote, nextOwnerTeamMemberId: nextOwner ? Number(nextOwner) : null, nextAction })} className="mt-6 h-11 w-full bg-[#1D5C63] hover:bg-[#164B50]"><ShieldCheck className="mr-2 h-4 w-4" />{phase === "start" ? "Record shift start" : "Record shift close"}</Button>}</section></div>;
}
