import { firebaseAuth, firebaseConfigured, firebaseDb } from "@/lib/firebase";
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, query, setDoc, updateDoc, where } from "firebase/firestore";
import { createUserWithEmailAndPassword, onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signOut, type User } from "firebase/auth";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Member = { id: number; userId: string; displayName: string; email: string; jobTitle: string; memberRole: "lead" | "coordinator" | "support"; initials: string; colour: string; status: "active" | "inactive" };
type Task = { id: number; workDate: string; title: string; detail: string | null; priority: "low" | "normal" | "high" | "critical"; status: "pending" | "in_progress" | "blocked" | "complete"; dueAt: number | null; assignedTeamMemberId: number | null; blockedReason: string | null; completedAt: number | null; createdAt: number; updatedAt: number };
type State = Record<string, any[]>;

const emptyState: State = { members: [], tasks: [], activities: [], templates: [], rota: [], handovers: [], issues: [], readiness: [], notes: [] };
const leadEmail = "bc@swanstravel.com";

type WorkspaceContextValue = {
  authUser: User | null; profile: Member | null; loading: boolean; error: Error | null; state: State; refresh: () => Promise<void>;
  signIn: (email: string, password: string) => Promise<void>; signUp: (name: string, email: string, password: string) => Promise<void>; resetPassword: (email: string) => Promise<void>; logout: () => Promise<void>;
  add: (collectionName: string, value: Record<string, unknown>) => Promise<any>; patch: (collectionName: string, id: string, value: Record<string, unknown>) => Promise<void>; remove: (collectionName: string, id: string) => Promise<void>; createTeamMember: (value: Record<string, unknown>) => Promise<any>;
};
const WorkspaceContext = createContext<WorkspaceContextValue | null>(null);

const collectionMap: Record<string, string> = { members: "ops_members", tasks: "ops_tasks", activities: "ops_task_activity", templates: "ops_templates", rota: "ops_rota", handovers: "ops_handovers", issues: "ops_issues", readiness: "ops_readiness", notes: "ops_performance_notes" };
const safeArray = (value: any) => Array.isArray(value) ? value : [];
const now = () => Date.now();
const numericId = () => Date.now() + Math.floor(Math.random() * 1_000);

export function WorkspaceProvider({ children }: { children: ReactNode }) {
  const [authUser, setAuthUser] = useState<User | null>(null); const [profile, setProfile] = useState<Member | null>(null); const [state, setState] = useState<State>(emptyState); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null);
  const refresh = useCallback(async () => { const database = firebaseDb; if (!database || !authUser) return; const pairs = await Promise.all(Object.entries(collectionMap).map(async ([key, name]) => [key, (await getDocs(collection(database, name))).docs.map(snapshot => ({ _docId: snapshot.id, ...snapshot.data() }))] as const)); setState(Object.fromEntries(pairs) as State); }, [authUser]);
  useEffect(() => { const database = firebaseDb; if (!firebaseAuth || !database) { setLoading(false); return; } return onAuthStateChanged(firebaseAuth, async user => { setAuthUser(user); setProfile(null); setState(emptyState); setError(null); if (!user) { setLoading(false); return; } try { const snapshot = await getDoc(doc(database, "ops_members", user.uid)); if (snapshot.exists()) setProfile({ userId: user.uid, ...snapshot.data() } as Member); setLoading(false); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Unable to load your operations profile.")); setLoading(false); } }); }, []);
  useEffect(() => { const database = firebaseDb; if (!database || !authUser || !profile) return; const unsubscribers = Object.entries(collectionMap).map(([key, name]) => onSnapshot(collection(database, name), snapshot => setState(current => ({ ...current, [key]: snapshot.docs.map(item => ({ _docId: item.id, ...item.data() })) })), reason => setError(reason instanceof Error ? reason : new Error("Unable to load workspace data.")))); return () => unsubscribers.forEach(unsubscribe => unsubscribe()); }, [authUser, profile]);
  const signIn = useCallback(async (email: string, password: string) => { if (!firebaseAuth) throw new Error("Firebase is not configured yet."); await signInWithEmailAndPassword(firebaseAuth, email.trim().toLowerCase(), password); }, []);
  const signUp = useCallback(async (name: string, email: string, password: string) => { if (!firebaseAuth || !firebaseDb) throw new Error("Firebase is not configured yet."); const normalized = email.trim().toLowerCase(); if (!normalized.endsWith("@swanstravel.com")) throw new Error("This workspace is restricted to approved Swans Travel work-email accounts."); const credential = await createUserWithEmailAndPassword(firebaseAuth, normalized, password); const invitation = await getDoc(doc(firebaseDb, "ops_invites", normalized)); const invited = invitation.exists() ? invitation.data() : null; if (normalized !== leadEmail && !invited) { await signOut(firebaseAuth); throw new Error("Your work email has not been invited yet. Ask the operations lead to add you to the team directory first."); } const displayName = invited?.displayName || name.trim(); const memberProfile: Member = { id: invited?.id || now(), userId: credential.user.uid, displayName, email: normalized, jobTitle: invited?.jobTitle || "Operations Lead", memberRole: normalized === leadEmail ? "lead" : invited?.memberRole || "support", initials: invited?.initials || displayName.split(" ").map((part: string) => part[0]).join("").slice(0, 3).toUpperCase(), colour: invited?.colour || "#1D5C63", status: "active" }; await setDoc(doc(firebaseDb, "ops_members", credential.user.uid), { ...memberProfile, createdAt: now(), updatedAt: now() }); setProfile(memberProfile); await sendEmailVerification(credential.user); }, []);
  const resetPassword = useCallback(async (email: string) => { if (!firebaseAuth) throw new Error("Firebase is not configured yet."); await sendPasswordResetEmail(firebaseAuth, email.trim().toLowerCase()); }, []);
  const logout = useCallback(async () => { if (firebaseAuth) await signOut(firebaseAuth); }, []);
  const add = useCallback(async (collectionName: string, value: Record<string, unknown>) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); const result = await addDoc(collection(firebaseDb, collectionMap[collectionName]), { ...value, createdAt: now(), updatedAt: now() }); return { _docId: result.id, ...value }; }, []);
  const patch = useCallback(async (collectionName: string, id: string, value: Record<string, unknown>) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); await updateDoc(doc(firebaseDb, collectionMap[collectionName], id), { ...value, updatedAt: now() }); }, []);
  const remove = useCallback(async (collectionName: string, id: string) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); await deleteDoc(doc(firebaseDb, collectionMap[collectionName], id)); }, []);
  const createTeamMember = useCallback(async (value: Record<string, unknown>) => { if (!firebaseDb || !profile || profile.memberRole !== "lead") throw new Error("Only the operations lead can add a team member."); const email = String(value.email || "").trim().toLowerCase(); if (!email.endsWith("@swanstravel.com")) throw new Error("Use the colleague’s Swans Travel work email."); const memberId = numericId(); await setDoc(doc(firebaseDb, "ops_invites", email), { ...value, id: memberId, email, createdAt: now(), createdBy: profile.userId }); return { id: memberId, ...value, email, status: "invited" }; }, [profile]);
  const value = useMemo(() => ({ authUser, profile, loading, error, state, refresh, signIn, signUp, resetPassword, logout, add, patch, remove, createTeamMember }), [authUser, profile, loading, error, state, refresh, signIn, signUp, resetPassword, logout, add, patch, remove, createTeamMember]); return <WorkspaceContext.Provider value={value}>{children}</WorkspaceContext.Provider>;
}
export function useWorkspace() { const context = useContext(WorkspaceContext); if (!context) throw new Error("WorkspaceProvider is missing."); return context; }
export function requireLead(profile: Member | null) { if (!profile || profile.memberRole !== "lead") throw new Error("Only the operations lead can perform that action."); }
export function hydrateMember(state: State, memberId?: number | null) { return state.members.find(member => member.id === memberId) ?? null; }
