import { firebaseAuth, firebaseConfigured, firebaseDb, firebaseStorage } from "@/lib/firebase";
import { omitUndefinedFields } from "@/lib/firestorePayload";
import { buildTaskAssignmentNotification } from "@/lib/collaboration";
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, query, setDoc, updateDoc, where } from "firebase/firestore";
import { createUserWithEmailAndPassword, onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signOut, type User } from "firebase/auth";
import { deleteObject, getDownloadURL, ref as storageRef, uploadBytes } from "firebase/storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { activitySummary } from "@/lib/auditHistory";

type Member = { id: number; userId: string; displayName: string; email: string; jobTitle: string; memberRole: "lead" | "manager" | "coordinator" | "dispatcher" | "on_call" | "viewer" | "support"; initials: string; colour: string; status: "active" | "inactive" | "invited" };
type Task = { id: number; workDate: string; title: string; detail: string | null; priority: "low" | "normal" | "high" | "critical"; status: "pending" | "in_progress" | "blocked" | "complete"; dueAt: number | null; assignedTeamMemberId: number | null; blockedReason: string | null; completedAt: number | null; createdAt: number; updatedAt: number };
type TaskAttachmentInput = { taskId: number; file: File };
type TaskAttachment = { _docId: string; id: number; taskId: number; name: string; contentType: string; size: number; storagePath: string; downloadUrl: string; uploadedByUserId: string; uploadedByTeamMemberId: number; uploadedByName: string; createdAt: number; };
type State = Record<string, any[]>;

const emptyState: State = { members: [], tasks: [], activities: [], taskAttachments: [], templates: [], rota: [], handovers: [], issues: [], readiness: [], notes: [], chatMessages: [], notifications: [], onCallItems: [], helpRequests: [], shiftPrompts: [], presence: [], reportViews: [], auditLogs: [] };
const leadEmail = "bc@swanstravel.com";

type WorkspaceContextValue = {
  authUser: User | null; profile: Member | null; loading: boolean; error: Error | null; state: State; refresh: () => Promise<void>;
  signIn: (email: string, password: string) => Promise<void>; signUp: (name: string, email: string, password: string) => Promise<void>; resetPassword: (email: string) => Promise<void>; logout: () => Promise<void>;
  add: (collectionName: string, value: Record<string, unknown>) => Promise<any>; patch: (collectionName: string, id: string, value: Record<string, unknown>) => Promise<void>; remove: (collectionName: string, id: string) => Promise<void>; uploadTaskAttachment: (input: TaskAttachmentInput) => Promise<TaskAttachment>; removeTaskAttachment: (attachment: TaskAttachment) => Promise<void>; createTeamMember: (value: Record<string, unknown>) => Promise<any>; cancelTeamInvitation: (email: string) => Promise<void>;
};
const WorkspaceContext = createContext<WorkspaceContextValue | null>(null);

const collectionMap: Record<string, string> = { members: "ops_members", tasks: "ops_tasks", activities: "ops_task_activity", taskAttachments: "ops_task_attachments", templates: "ops_templates", rota: "ops_rota", handovers: "ops_handovers", issues: "ops_issues", readiness: "ops_readiness", notes: "ops_performance_notes", chatMessages: "ops_chat_messages", notifications: "ops_notifications", onCallItems: "ops_on_call_items", helpRequests: "ops_help_requests", shiftPrompts: "ops_shift_prompts", presence: "ops_presence", reportViews: "ops_report_views", auditLogs: "ops_audit_logs" };
const safeArray = (value: any) => Array.isArray(value) ? value : [];
const now = () => Date.now();
const numericId = () => Date.now() + Math.floor(Math.random() * 1_000);
const asMember = (value: unknown) => value as Member;

async function queueTaskAssignmentEmail(authUser: User | null, task: Record<string, unknown>) {
  const recipientEmail = typeof task.assignedEmail === "string" ? task.assignedEmail : "";
  const taskTitle = typeof task.title === "string" ? task.title : "";
  if (!authUser || !recipientEmail || !taskTitle) return;
  try {
    const idToken = await authUser.getIdToken();
    await fetch("/api/task-assignment-email", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${idToken}` }, body: JSON.stringify({ recipientEmail, taskTitle, detail: typeof task.detail === "string" ? task.detail : "", dueAt: typeof task.dueAt === "number" ? task.dueAt : null }) });
  } catch {
    // In-app notifications remain available even when the optional external email relay is unavailable.
  }
}

export function WorkspaceProvider({ children }: { children: ReactNode }) {
  const [authUser, setAuthUser] = useState<User | null>(null); const [profile, setProfile] = useState<Member | null>(null); const [state, setState] = useState<State>(emptyState); const [memberProfiles, setMemberProfiles] = useState<Member[]>([]); const [invitations, setInvitations] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); const signedInAuditUid = useRef<string | null>(null);
  const workspaceState = useMemo(() => { const members = [...memberProfiles, ...invitations.filter(invitation => !memberProfiles.some(member => member.email === invitation.email))]; return { ...state, members }; }, [state, memberProfiles, invitations]);
  const refresh = useCallback(async () => { const database = firebaseDb; if (!database || !authUser) return; const pairs = await Promise.all(Object.entries(collectionMap).filter(([key]) => (key !== "reportViews" && key !== "auditLogs") || profile?.memberRole === "lead").map(async ([key, name]) => { const source = key === "notifications" ? query(collection(database, name), where("recipientEmail", "==", authUser.email || "")) : collection(database, name); return [key, (await getDocs(source)).docs.map(snapshot => ({ _docId: snapshot.id, ...snapshot.data() }))] as const; })); const records = Object.fromEntries(pairs) as State; setMemberProfiles((records.members ?? []) as Member[]); setState({ ...records, members: [] }); }, [authUser, profile]);
  useEffect(() => { const database = firebaseDb; if (!firebaseAuth || !database) { setLoading(false); return; } return onAuthStateChanged(firebaseAuth, async user => { setAuthUser(user); setProfile(null); setState(emptyState); setMemberProfiles([]); setInvitations([]); setError(null); if (!user) { signedInAuditUid.current = null; setLoading(false); return; } try { const snapshot = await getDoc(doc(database, "ops_members", user.uid)); if (snapshot.exists()) { const memberProfile = { userId: user.uid, ...snapshot.data() } as Member; setProfile(memberProfile); if (signedInAuditUid.current !== user.uid) { signedInAuditUid.current = user.uid; void addDoc(collection(database, "ops_audit_logs"), { actorUserId: user.uid, actorName: memberProfile.displayName, actorInitials: memberProfile.initials, actorColour: memberProfile.colour, action: "signed_in", targetType: "session", summary: "Signed in to the Command Centre.", createdAt: now() }); } } setLoading(false); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Unable to load your operations profile.")); setLoading(false); } }); }, []);
  useEffect(() => { const database = firebaseDb; if (!database || !authUser || !profile) return; const unsubscribers = Object.entries(collectionMap).filter(([key]) => (key !== "reportViews" && key !== "auditLogs") || profile.memberRole === "lead").map(([key, name]) => { const source = key === "notifications" ? query(collection(database, name), where("recipientEmail", "==", profile.email)) : collection(database, name); return onSnapshot(source, snapshot => { const rows = snapshot.docs.map(item => ({ _docId: item.id, ...item.data() })); if (key === "members") setMemberProfiles(rows.map(asMember)); else setState(current => ({ ...current, [key]: rows })); }, reason => setError(reason instanceof Error ? reason : new Error("Unable to load workspace data."))); }); return () => unsubscribers.forEach(unsubscribe => unsubscribe()); }, [authUser, profile]);
  useEffect(() => { const database = firebaseDb; if (!database || profile?.memberRole !== "lead") { setInvitations([]); return; } return onSnapshot(collection(database, "ops_invites"), snapshot => setInvitations(snapshot.docs.map(item => asMember({ _docId: item.id, userId: "", ...item.data(), status: "invited" }))), reason => setError(reason instanceof Error ? reason : new Error("Unable to load invited team profiles."))); }, [profile]);
  useEffect(() => { const database = firebaseDb; if (!database || !authUser || !profile) return; const updatePresence = () => { if (document.visibilityState === "visible") void setDoc(doc(database, "ops_presence", authUser.uid), { userId: authUser.uid, teamMemberId: profile.id, displayName: profile.displayName, initials: profile.initials, colour: profile.colour, lastActiveAt: now() }, { merge: true }); }; updatePresence(); const interval = window.setInterval(updatePresence, 60_000); document.addEventListener("visibilitychange", updatePresence); return () => { window.clearInterval(interval); document.removeEventListener("visibilitychange", updatePresence); }; }, [authUser, profile]);
  const signIn = useCallback(async (email: string, password: string) => { if (!firebaseAuth) throw new Error("Firebase is not configured yet."); await signInWithEmailAndPassword(firebaseAuth, email.trim().toLowerCase(), password); }, []);
  const signUp = useCallback(async (name: string, email: string, password: string) => { if (!firebaseAuth || !firebaseDb) throw new Error("Firebase is not configured yet."); const normalized = email.trim().toLowerCase(); if (!normalized.endsWith("@swanstravel.com")) throw new Error("This workspace is restricted to approved Swans Travel work-email accounts."); const credential = await createUserWithEmailAndPassword(firebaseAuth, normalized, password); const invitation = await getDoc(doc(firebaseDb, "ops_invites", normalized)); const invited = invitation.exists() ? invitation.data() : null; if (normalized !== leadEmail && !invited) { await signOut(firebaseAuth); throw new Error("Your work email has not been invited yet. Ask the operations lead to add you to the team directory first."); } const displayName = invited?.displayName || name.trim(); const memberProfile: Member = { id: invited?.id || now(), userId: credential.user.uid, displayName, email: normalized, jobTitle: invited?.jobTitle || "Operations Lead", memberRole: normalized === leadEmail ? "lead" : invited?.memberRole || "support", initials: invited?.initials || displayName.split(" ").map((part: string) => part[0]).join("").slice(0, 3).toUpperCase(), colour: invited?.colour || "#1D5C63", status: "active" }; await setDoc(doc(firebaseDb, "ops_members", credential.user.uid), { ...memberProfile, createdAt: now(), updatedAt: now() }); setProfile(memberProfile); await sendEmailVerification(credential.user); }, []);
  const resetPassword = useCallback(async (email: string) => { if (!firebaseAuth) throw new Error("Firebase is not configured yet."); await sendPasswordResetEmail(firebaseAuth, email.trim().toLowerCase()); }, []);
  const logout = useCallback(async () => { if (firebaseAuth) await signOut(firebaseAuth); }, []);
  const writeAudit = useCallback((action: "created" | "updated" | "deleted", collectionName: string, targetId: string, value: Record<string, unknown> = {}) => { if (!firebaseDb || !authUser || !profile || !activitySummary || !collectionMap[collectionName]) return; void addDoc(collection(firebaseDb, "ops_audit_logs"), { actorUserId: authUser.uid, actorName: profile.displayName, actorInitials: profile.initials, actorColour: profile.colour, action, targetType: collectionName, targetId, summary: activitySummary(action, collectionName, value), createdAt: now() }); }, [authUser, profile]);
  const add = useCallback(async (collectionName: string, value: Record<string, unknown>) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); const payload = omitUndefinedFields({ ...value, createdAt: now(), updatedAt: now() }); const result = await addDoc(collection(firebaseDb, collectionMap[collectionName]), payload); if (collectionName !== "auditLogs" && collectionName !== "notifications") writeAudit("created", collectionName, result.id, payload); if (collectionName === "tasks" && typeof payload.assignedEmail === "string" && payload.assignedEmail) { try { const createdAt = now(); await addDoc(collection(firebaseDb, collectionMap.notifications), buildTaskAssignmentNotification({ id: typeof payload.id === "number" ? payload.id : null, assignedEmail: payload.assignedEmail, title: String(payload.title || "A new task") }, numericId(), createdAt)); } finally { void queueTaskAssignmentEmail(authUser, payload); } } return { _docId: result.id, ...payload }; }, [authUser, writeAudit]);
  const patch = useCallback(async (collectionName: string, id: string, value: Record<string, unknown>) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); const changes = omitUndefinedFields({ ...value, updatedAt: now() }); await updateDoc(doc(firebaseDb, collectionMap[collectionName], id), changes); if (collectionName !== "auditLogs" && collectionName !== "notifications" && collectionName !== "presence") writeAudit("updated", collectionName, id, changes); if (collectionName === "members" && id === authUser?.uid) setProfile(current => current ? { ...current, ...changes } as Member : current); }, [authUser, writeAudit]);
  const remove = useCallback(async (collectionName: string, id: string) => { if (!firebaseDb) throw new Error("Firebase is not configured yet."); await deleteDoc(doc(firebaseDb, collectionMap[collectionName], id)); if (collectionName !== "auditLogs" && collectionName !== "notifications") writeAudit("deleted", collectionName, id); }, [writeAudit]);
  const uploadTaskAttachment = useCallback(async ({ taskId, file }: TaskAttachmentInput) => {
    if (!firebaseDb || !firebaseStorage || !authUser || !profile) throw new Error("You must be signed in to attach a file.");
    if (file.size > 10 * 1024 * 1024) throw new Error("Attachments must be 10 MB or smaller.");
    const safeName = file.name.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-").slice(-120) || "attachment";
    const storagePath = `ops_tasks/${taskId}/${authUser.uid}/${Date.now()}-${safeName}`;
    const fileRef = storageRef(firebaseStorage, storagePath);
    await uploadBytes(fileRef, file, { contentType: file.type || "application/octet-stream" });
    try {
      const downloadUrl = await getDownloadURL(fileRef);
      const payload = { id: numericId(), taskId, name: file.name, contentType: file.type || "application/octet-stream", size: file.size, storagePath, downloadUrl, uploadedByUserId: authUser.uid, uploadedByTeamMemberId: profile.id, uploadedByName: profile.displayName };
      const result = await addDoc(collection(firebaseDb, collectionMap.taskAttachments), { ...payload, createdAt: now(), updatedAt: now() });
      writeAudit("created", "taskAttachments", result.id, payload);
      return { _docId: result.id, ...payload, createdAt: now() } as TaskAttachment;
    } catch (reason) {
      await deleteObject(fileRef).catch(() => undefined);
      throw reason;
    }
  }, [authUser, profile, writeAudit]);
  const removeTaskAttachment = useCallback(async (attachment: TaskAttachment) => {
    if (!firebaseDb || !firebaseStorage || !profile || !["lead", "manager"].includes(profile.memberRole)) throw new Error("Only an operations manager can remove task attachments.");
    const fileRef = storageRef(firebaseStorage, attachment.storagePath);
    try { await deleteObject(fileRef); } catch (reason) { if ((reason as { code?: string })?.code !== "storage/object-not-found") throw reason; }
    await deleteDoc(doc(firebaseDb, collectionMap.taskAttachments, attachment._docId));
    writeAudit("deleted", "taskAttachments", attachment._docId, { taskId: attachment.taskId, name: attachment.name });
  }, [profile, writeAudit]);
  const createTeamMember = useCallback(async (value: Record<string, unknown>) => { if (!firebaseDb || !profile || profile.memberRole !== "lead") throw new Error("Only the operations lead can add a team member."); const email = String(value.email || "").trim().toLowerCase(); if (!email.endsWith("@swanstravel.com")) throw new Error("Use the colleague’s Swans Travel work email."); const memberId = numericId(); const invitation: Member & { createdAt: number; createdBy: string } = { id: memberId, userId: "", email, displayName: String(value.displayName), jobTitle: String(value.jobTitle), memberRole: value.memberRole as Member["memberRole"], initials: String(value.initials), colour: String(value.colour), status: "invited", createdAt: now(), createdBy: profile.userId }; await setDoc(doc(firebaseDb, "ops_invites", email), invitation); writeAudit("created", "members", email, invitation); setInvitations(current => [...current.filter(member => member.email !== email), invitation]); return invitation; }, [profile, writeAudit]);
  const cancelTeamInvitation = useCallback(async (email: string) => { if (!firebaseDb || profile?.memberRole !== "lead") throw new Error("Only the operations lead can cancel an invitation."); await deleteDoc(doc(firebaseDb, "ops_invites", email)); writeAudit("deleted", "members", email, { email }); setInvitations(current => current.filter(member => member.email !== email)); }, [profile, writeAudit]);
  const value = useMemo(() => ({ authUser, profile, loading, error, state: workspaceState, refresh, signIn, signUp, resetPassword, logout, add, patch, remove, uploadTaskAttachment, removeTaskAttachment, createTeamMember, cancelTeamInvitation }), [authUser, profile, loading, error, workspaceState, refresh, signIn, signUp, resetPassword, logout, add, patch, remove, uploadTaskAttachment, removeTaskAttachment, createTeamMember, cancelTeamInvitation]); return <WorkspaceContext.Provider value={value}>{children}</WorkspaceContext.Provider>;
}
export function useWorkspace() { const context = useContext(WorkspaceContext); if (!context) throw new Error("WorkspaceProvider is missing."); return context; }
export function requireLead(profile: Member | null) { if (!profile || profile.memberRole !== "lead") throw new Error("Only the operations lead can perform that action."); }
export function requireOperationsManager(profile: Member | null) { if (!profile || !["lead", "manager"].includes(profile.memberRole)) throw new Error("Only an operations lead or manager can perform that action."); }
export function hydrateMember(state: State, memberId?: number | null) { return state.members.find(member => member.id === memberId) ?? null; }
